### ISSUE TITLE
EventData throws a NullPointerException

### ISSUE THREAD

**Issue by MoonBow-1** [teragrep/aer_02#6]
**Description**

Currently there is an NPE when reading Events from an Event Hub, likely cause is the wait time for the Azure Function that waits for additional elements to be gathered for a batch.

Resources about this:

- https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.eventprocessorclientoptions.maximumwaittime?view=azure-dotnet#azure-messaging-eventhubs-eventprocessorclientoptions-maximumwaittime

- https://learn.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.processor.processeventargs.hasevent?view=azure-dotnet#azure-messaging-eventhubs-processor-processeventargs-hasevent

**Comment by MoonBow-1** [comment]
Currently switching from EventData array to String array as the trigger input, and removing bad bindings, which result in Index out of bounds exceptions.

Tomorrow consumer should be refactored to only accept the remaining bindings

**Comment by eemhu** [comment]
fixed in #8
